version: '3.8'

services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www
    volumes:
      - ./www:/var/www
      - ./php/conf/local.ini:/usr/local/etc/php/conf.d/local.ini

  webserver:
    image: nginx:latest
    container_name: webserver
    ports:
      - "8080:80"
#      - "443:443"
    volumes:
      - ./www:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  db:
    image: mysql:5.7
    container_name: db
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: yourDatabaseName
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: yourPassword